NAME = cuda-toolkit
VERSION    = 7.5.18
RELEASE = 1
MAJOR_VERSION = 7.0
CUDNN_VERSION = 4.0

DISTDIR = distro

TOOLKIT_ARCH   = linux
TOOLKIT_SUFFIX = run
TOOLKIT_DISTRO = cuda_$(VERSION)_$(TOOLKIT_ARCH).$(TOOLKIT_SUFFIX)

