NAME = cuda-toolkit
VERSION    = 8.0.61
RELEASE = 1
MAJOR_VERSION = 8.0
CUDNN_VERSION = 5.1

DISTDIR = distro

TOOLKIT_ARCH   = linux
TOOLKIT_SUFFIX = run
TOOLKIT_DISTRO = cuda_$(VERSION)_*_$(TOOLKIT_ARCH).$(TOOLKIT_SUFFIX)

